#!/bin/bash

versions="3.8 3.9 3.10 3.11 3.12 3.13"

function run_version_tests {
    if [ "--build" = $2 ]
    then
        args="--inplace --force"
        LAZYCSV_INCLUDE_NUMPY=1 LAZYCSV_INDEX_DTYPE=uint8_t \
            python setup.py build_ext $args &> /dev/null
    fi
    python -m pytest
}

function run_benchmarks {
    python ./tests/benchmark_lazy.py
}

function print_help {
    echo "bash commands:"
    echo "- bench: run benchmarks"
    echo "- build: build extension with numpy enabled"
    echo "- test: run test suite"
    echo "- setup: install pyenv versions and dependencies"
    echo "- tox: run tox"
}

function run_setup {
    if [ -z $(command -v pyenv) ]
    then
        echo "setup requires pyenv"
        exit 1
    fi

    for version in $versions
    do
        pyenv install -s $version
    done

    pyenv local $versions

    for version in $versions
    do
        python$version -m pip install numpy pytest
        python$version -m pip install -e .
    done

    python3.11 -m pip install tox
}

function run_tox {
    python3.11 -m tox
}

function run_debug {
    LAZYCSV_INCLUDE_NUMPY=1 \
    LAZYCSV_INDEX_DTYPE="uint8_t" \
    LAZYCSV_DEBUG=1 \
    CFLAGS="-O0" \
    python setup.py build_ext --inplace --force \
    && gdb --args python -m pytest ${@:2}
}

function run_build {
    LAZYCSV_INCLUDE_NUMPY=1 \
    python setup.py build_ext --inplace --force
}

case $1 in
    setup) run_setup $@ ;;
    test) run_version_tests $@ ;;
    bench) run_benchmarks $@ ;;
    build) run_build $@ ;;
    debug) run_debug $@ ;;
    tox) run_tox $@ ;;
    *) print_help $@ ;;
esac
