[tox]
envlist = py38,py39,py310,py311,py312,py313

[testenv]
deps =
    pytest
    numpy
setenv =
    LAZYCSV_INCLUDE_NUMPY=1
pass_env =
    LAZYCSV_INCLUDE_NUMPY
commands =
    python -m pytest {posargs}
